# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ff9da4d8cd774d626c2cf2ce1eab75ebf65cc5d2d7297121a5007d1d17bc55384e5f49e567ac085ac77ae56bed5c90c6c04ed13dd10489fe8612e369310d836

test:
  secret_key_base: 358891c222abd8da81cece87e1362eaec798395cb099a14048bce6bb4e4499ac56b79dee69b09f289419d4b9017ec6b21f6e530a84027fd92656fcc64b20c3c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
